name: CI

on:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  generateMatrix:
    name: "Generate matrix from cabal"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v2
      - name: Extract the tested GHC versions
        id: set-matrix
        run: |
          wget https://github.com/Kleidukos/get-tested/releases/download/v0.1.4.0/get-tested-0.1.4.0-linux-amd64 -O get-tested
          chmod +x get-tested
          ./get-tested --ubuntu literatex.cabal >> $GITHUB_OUTPUT

  latest-cabal:
    name: "Cabal: GHC ${{ matrix.ghc }} on ${{ matrix.os }}"
    needs: generateMatrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJSON(needs.generateMatrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: latest
      - name: Build
        run: cabal new-build --enable-tests --enable-benchmarks
      - name: Test
        run: cabal new-test --enable-tests

  stack:
    name: "Stack: GHC ${{ matrix.ghc }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.2.2', '8.4.4', '8.6.5', '8.8.4', '8.10.7', '9.0.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: latest
          enable-stack: true
          stack-version: latest
      - name: Cache ~/.stack
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack
      - name: Build
        run: stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
        env:
          STACK_YAML: stack-${{ matrix.ghc }}.yaml
      - name: Test
        run: stack test --system-ghc
        env:
          STACK_YAML: stack-${{ matrix.ghc }}.yaml

  cabal:
    name: "Cabal ${{ matrix.cabal }}: GHC 8.10.7"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ['3.6.0.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: 8.10.7
          cabal-version: ${{ matrix.cabal }}
      - name: Build
        run: cabal new-build --enable-tests --enable-benchmarks
      - name: Test
        run: cabal new-test --enable-tests
